- action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_on
  alias: Exterior Lights On Sunset
  id: 6c0e8b5e-7b34-4788-b688-7281bf38c1f1
  condition: []
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
- action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_off
  alias: Exterior Lights Off Sunset
  id: bcc267ca-a7b2-4d91-87f2-4a33084c7003
  condition: []
  trigger:
  - event: sunset
    offset: 02:00:00
    platform: sun
- action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_on
  alias: Exterior Lights On Sunrise
  id: 38784e20-d61a-4a25-949d-906abe934f20
  condition: []
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
- action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_off
  alias: Exterior Lights Off Sunrise
  id: 7fe29d59-4d1a-489c-a744-719739b66718
  condition: []
  trigger:
  - event: sunrise
    offset: 00:30:00
    platform: sun
- action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_on
  alias: Lights on Return Home
  condition:
  - after: sunset
    after_offset: 00:00
    before: sunrise
    before_offset: 00:00
    condition: sun
  id: e9e17fc8-bcfb-40ea-b964-8c1399718976
  trigger:
  - entity_id: device_tracker.9888b8344f47385657
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.samsungsmg891a
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
  alias: Lights off Leave Home
  id: 677c52be-2bdd-405f-9c21-dca63719f20d
  trigger:
  - entity_id: device_tracker.9888b8344f47385657
    event: leave
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.samsungsmg891a
    from: home
    platform: state
    to: not_home
- id: '1533417528548'
  alias: Kitchen Filter Change Notice
  trigger:
  - above: '243'
    entity_id: sensor.kitchen_water_filter_use
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: switch.kitchen_water_filter_change
    service: homeassistant.turn_on
  - data:
      message: Change kitchen water filter!
    service: notify.agmlego
- alias: Block Heater Weekday
  id: '1544066780497'
  trigger:
  - platform: time
    at: 05:00:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: '45'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.block_heater
- alias: Block Heater Error-Proof
  id: 5ed75204-0353-11e9-8eb2-f2801f1b9fd1
  trigger:
  - platform: state
    entity_id: switch.block_heater
    from: 'off'
    to: 'on'
    for:
      seconds: 30
  condition:
  - condition: numeric_state
    entity_id: sensor.current_block_heater
    below: 2.0
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.block_heater
  - service: notify.agmlego
    data:
      message: Block heater failed to reach current!
- id: '1545662750783'
  alias: Garage Door Testing
  trigger:
  - entity_id: binary_sensor.garage_man_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Garage door opened!
    service: notify.agmlego
